enum class ChannelName(val varName: String) {

    MANIFOLD_PRES("Manifold Pres"),
    AIR_DENSITY("AirDensity"),
    AIR_PRESSURE("AirPressure"),
    AIR_TEMP("AirTemp"),
    ALT("Alt"),
    BAT_VOLTS_ECU("Bat Volts ECU"),
    BEACON_INTERNAL("Beacon (Internal)"),
    BRAKE("Brake"),
    BRAKE_PEDAL_POS("Brake Pedal Pos"),
    BRAKE_ABS_ACTIVE("BrakeABSactive"),
    BRAKE_RAW("BrakeRaw"),
    CFSRRIDE_HEIGHT("CFSRrideHeight"),
    CHAN_AVG_LATENCY("ChanAvgLatency"),
    CHAN_CLOCK_SKEW("ChanClockSkew"),
    CHAN_LATENCY("ChanLatency"),
    CHAN_PARTNER_QUALITY("ChanPartnerQuality"),
    CHAN_QUALITY("ChanQuality"),
    CLUTCH("Clutch"),
    CLUTCH_PEDAL_POS("Clutch Pedal Pos"),
    CPU_USAGE_BG("CpuUsageBG"),
    CPU_USAGE_FG("CpuUsageFG"),
    DRIVER_MARKER("DriverMarker"),
    ENG_COOLANT_LEVEL("Eng Coolant Level"),
    ENG_OIL_PRESS("Eng Oil Press"),
    ENG_OIL_TEMP("Eng Oil Temp"),
    ENGINE_RPM("Engine RPM"),
    ENGINE_TEMP("Engine Temp"),
    ENGINE_0_RPM("Engine0_RPM"),
    ENGINE_WARNINGS("EngineWarnings"),
    ENTER_EXIT_RESET("EnterExitReset"),
    FAST_REPAIR_AVAILABLE("FastRepairAvailable"),
    FAST_REPAIR_USED("FastRepairUsed"),
    FOG_LEVEL("FogLevel"),
    FRAME_RATE("FrameRate"),
    FRONT_TIRE_SETS_AVAILABLE("FrontTireSetsAvailable"),
    FRONT_TIRE_SETS_USED("FrontTireSetsUsed"),
    FUEL_DENSITY("Fuel Density"),
    FUEL_LEVEL1("Fuel Level"),
    FUEL_PRES("Fuel Pres"),
    FUEL_REMAINING("Fuel Remaining"),
    FUEL_LEVEL2("FuelLevel"),
    FUEL_LEVEL_PCT("FuelLevelPct"),
    FUEL_PRESS("FuelPress"),
    FUEL_USE_PER_HOUR("FuelUsePerHour"),
    G_FORCE_LAT("G Force Lat"),
    G_FORCE_LONG("G Force Long"),
    G_FORCE_VERT("G Force Vert"),
    GPS_ALTITUDE("GPS Altitude"),
    GEAR("Gear"),
    GPU_USAGE("GpuUsage"),
    GROUND_SPEED("Ground Speed"),
    GYRO_PITCH_ANGLE("Gyro Pitch Angle"),
    GYRO_PITCH_VELOCITY("Gyro - Pitch Velocity"),
    GYRO_ROLL_ANGLE("Gyro Roll Angle"),
    GYRO__ROLL_VELOCITY("Gyro - Roll Velocity"),
    GYRO_YAW_ANGLE("Gyro Yaw Angle"),
    GYRO__YAW_VELOCITY("Gyro - Yaw Velocity"),
    HANDBRAKE_RAW("HandbrakeRaw"),
    IS_ON_TRACK("IsOnTrack"),
    IS_ON_TRACK_CAR("IsOnTrackCar"),
    LFTIRES_AVAILABLE("LFTiresAvailable"),
    LFTIRES_USED("LFTiresUsed"),
    LFBRAKE_LINE_PRESS("LFbrakeLinePress"),
    LFCOLD_PRESSURE("LFcoldPressure"),
    LFPRESSURE("LFpressure"),
    LFRIDE_HEIGHT("LFrideHeight"),
    LFSHOCK_DEFL("LFshockDefl"),
    LFSHOCK_VEL("LFshockVel"),
    LFSPEED("LFspeed"),
    LFTEMP_CL("LFtempCL"),
    LFTEMP_CM("LFtempCM"),
    LFTEMP_CR("LFtempCR"),
    LFTEMP_L("LFtempL"),
    LFTEMP_M("LFtempM"),
    LFTEMP_R("LFtempR"),
    LFWEAR_L("LFwearL"),
    LFWEAR_M("LFwearM"),
    LFWEAR_R("LFwearR"),
    LRTIRES_AVAILABLE("LRTiresAvailable"),
    LRTIRES_USED("LRTiresUsed"),
    LRBRAKE_LINE_PRESS("LRbrakeLinePress"),
    LRCOLD_PRESSURE("LRcoldPressure"),
    LRPRESSURE("LRpressure"),
    LRRIDE_HEIGHT("LRrideHeight"),
    LRSHOCK_DEFL("LRshockDefl"),
    LRSHOCK_VEL("LRshockVel"),
    LRSPEED("LRspeed"),
    LRTEMP_CL("LRtempCL"),
    LRTEMP_CM("LRtempCM"),
    LRTEMP_CR("LRtempCR"),
    LRTEMP_L("LRtempL"),
    LRTEMP_M("LRtempM"),
    LRTEMP_R("LRtempR"),
    LRWEAR_L("LRwearL"),
    LRWEAR_M("LRwearM"),
    LRWEAR_R("LRwearR"),
    LAP("Lap"),
    LAP_DISTANCE("Lap Distance"),
    LAP_NUMBER("Lap Number"),
    LAP_BEST_LAP("LapBestLap"),
    LAP_BEST_LAP_TIME("LapBestLapTime"),
    LAP_BEST_NLAP_LAP("LapBestNLapLap"),
    LAP_BEST_NLAP_TIME("LapBestNLapTime"),
    LAP_COMPLETED("LapCompleted"),
    LAP_CURRENT_LAP_TIME("LapCurrentLapTime"),
    LAP_DELTA_TO_BEST_LAP("LapDeltaToBestLap"),
    LAP_DELTA_TO_BEST_LAP_DD("LapDeltaToBestLap_DD"),
    LAP_DELTA_TO_BEST_LAP_OK("LapDeltaToBestLap_OK"),
    LAP_DELTA_TO_OPTIMAL_LAP("LapDeltaToOptimalLap"),
    LAP_DELTA_TO_OPTIMAL_LAP_DD("LapDeltaToOptimalLap_DD"),
    LAP_DELTA_TO_OPTIMAL_LAP_OK("LapDeltaToOptimalLap_OK"),
    LAP_DELTA_TO_SESSION_BEST_LAP("LapDeltaToSessionBestLap"),
    LAP_DELTA_TO_SESSION_BEST_LAP_DD("LapDeltaToSessionBestLap_DD"),
    LAP_DELTA_TO_SESSION_BEST_LAP_OK("LapDeltaToSessionBestLap_OK"),
    LAP_DELTA_TO_SESSION_LASTL_LAP("LapDeltaToSessionLastlLap"),
    LAP_DELTA_TO_SESSION_LASTL_LAP_DD("LapDeltaToSessionLastlLap_DD"),
    LAP_DELTA_TO_SESSION_LASTL_LAP_OK("LapDeltaToSessionLastlLap_OK"),
    LAP_DELTA_TO_SESSION_OPTIMAL_LAP("LapDeltaToSessionOptimalLap"),
    LAP_DELTA_TO_SESSION_OPTIMAL_LAP_DD("LapDeltaToSessionOptimalLap_DD"),
    LAP_DELTA_TO_SESSION_OPTIMAL_LAP_OK("LapDeltaToSessionOptimalLap_OK"),
    LAP_DIST("LapDist"),
    LAP_DIST_PCT("LapDistPct"),
    LAP_LAS_NLAP_SEQ("LapLasNLapSeq"),
    LAP_LAST_LAP_TIME("LapLastLapTime"),
    LAP_LAST_NLAP_TIME("LapLastNLapTime"),
    LAT("Lat"),
    LAT_ACCEL("LatAccel"),
    LATITUDE_DEGREES("Latitude Degrees"),
    LATITUDE_MINUTE_FRACTION("Latitude Minute fraction"),
    LATITUDE_MINUTES("Latitude Minutes"),
    LEFT_TIRE_SETS_AVAILABLE("LeftTireSetsAvailable"),
    LEFT_TIRE_SETS_USED("LeftTireSetsUsed"),
    LON("Lon"),
    LONG_ACCEL("LongAccel"),
    LONGITUDE_DEGREES("Longitude Degrees"),
    LONGITUDE_MINUTE_FRACTION("Longitude Minute - fraction"),
    LONGITUDE_MINUTES("Longitude Minutes"),
    MANIFOLD_PRESS("ManifoldPress"),
    MANUAL_BOOST("ManualBoost"),
    MANUAL_NO_BOOST("ManualNoBoost"),
    MEM_PAGE_FAULT_SEC("MemPageFaultSec"),
    MEM_SOFT_PAGE_FAULT_SEC("MemSoftPageFaultSec"),
    OIL_LEVEL("OilLevel"),
    OIL_PRESS("OilPress"),
    OIL_TEMP("OilTemp"),
    ON_PIT_ROAD("OnPitRoad"),
    PACE_MODE("PaceMode"),
    PIT_OPT_REPAIR_LEFT("PitOptRepairLeft"),
    PIT_REPAIR_LEFT("PitRepairLeft"),
    PIT_SV_FLAGS("PitSvFlags"),
    PIT_SV_FUEL("PitSvFuel"),
    PIT_SV_LFP("PitSvLFP"),
    PIT_SV_LRP("PitSvLRP"),
    PIT_SV_RFP("PitSvRFP"),
    PIT_SV_RRP("PitSvRRP"),
    PIT_SV_TIRE_COMPOUND("PitSvTireCompound"),
    PITCH("Pitch"),
    PITCH_RATE("PitchRate"),
    PITS_OPEN("PitsOpen"),
    PITSTOP_ACTIVE("PitstopActive"),
    PLAYER_CAR_CLASS("PlayerCarClass"),
    PLAYER_CAR_CLASS_POSITION("PlayerCarClassPosition"),
    PLAYER_CAR_DRIVER_INCIDENT_COUNT("PlayerCarDriverIncidentCount"),
    PLAYER_CAR_DRY_TIRE_SET_LIMIT("PlayerCarDryTireSetLimit"),
    PLAYER_CAR_IDX("PlayerCarIdx"),
    PLAYER_CAR_IN_PIT_STALL("PlayerCarInPitStall"),
    PLAYER_CAR_MY_INCIDENT_COUNT("PlayerCarMyIncidentCount"),
    PLAYER_CAR_PIT_SV_STATUS("PlayerCarPitSvStatus"),
    PLAYER_CAR_POSITION("PlayerCarPosition"),
    PLAYER_CAR_POWER_ADJUST("PlayerCarPowerAdjust"),
    PLAYER_CAR_TEAM_INCIDENT_COUNT("PlayerCarTeamIncidentCount"),
    PLAYER_CAR_TOW_TIME("PlayerCarTowTime"),
    PLAYER_CAR_WEIGHT_PENALTY("PlayerCarWeightPenalty"),
    PLAYER_FAST_REPAIRS_USED("PlayerFastRepairsUsed"),
    PLAYER_TIRE_COMPOUND("PlayerTireCompound"),
    PLAYER_TRACK_SURFACE("PlayerTrackSurface"),
    PLAYER_TRACK_SURFACE_MATERIAL("PlayerTrackSurfaceMaterial"),
    PUSH_TO_PASS("PushToPass"),
    RFTIRES_AVAILABLE("RFTiresAvailable"),
    RFTIRES_USED("RFTiresUsed"),
    RFBRAKE_LINE_PRESS("RFbrakeLinePress"),
    RFCOLD_PRESSURE("RFcoldPressure"),
    RFPRESSURE("RFpressure"),
    RFRIDE_HEIGHT("RFrideHeight"),
    RFSHOCK_DEFL("RFshockDefl"),
    RFSHOCK_VEL("RFshockVel"),
    RFSPEED("RFspeed"),
    RFTEMP_CL("RFtempCL"),
    RFTEMP_CM("RFtempCM"),
    RFTEMP_CR("RFtempCR"),
    RFTEMP_L("RFtempL"),
    RFTEMP_M("RFtempM"),
    RFTEMP_R("RFtempR"),
    RFWEAR_L("RFwearL"),
    RFWEAR_M("RFwearM"),
    RFWEAR_R("RFwearR"),
    RPM("RPM"),
    RRTIRES_AVAILABLE("RRTiresAvailable"),
    RRTIRES_USED("RRTiresUsed"),
    RRBRAKE_LINE_PRESS("RRbrakeLinePress"),
    RRCOLD_PRESSURE("RRcoldPressure"),
    RRPRESSURE("RRpressure"),
    RRRIDE_HEIGHT("RRrideHeight"),
    RRSHOCK_DEFL("RRshockDefl"),
    RRSHOCK_VEL("RRshockVel"),
    RRSPEED("RRspeed"),
    RRTEMP_CL("RRtempCL"),
    RRTEMP_CM("RRtempCM"),
    RRTEMP_CR("RRtempCR"),
    RRTEMP_L("RRtempL"),
    RRTEMP_M("RRtempM"),
    RRTEMP_R("RRtempR"),
    RRWEAR_L("RRwearL"),
    RRWEAR_M("RRwearM"),
    RRWEAR_R("RRwearR"),
    REAR_TIRE_SETS_AVAILABLE("RearTireSetsAvailable"),
    REAR_TIRE_SETS_USED("RearTireSetsUsed"),
    RELATIVE_HUMIDITY("RelativeHumidity"),
    RIDE_HEIGHT_FL("Ride Height FL"),
    RIDE_HEIGHT_FR("Ride Height FR"),
    RIDE_HEIGHT_FS("Ride Height FS"),
    RIDE_HEIGHT_RL("Ride Height RL"),
    RIDE_HEIGHT_RR("Ride Height RR"),
    RIGHT_TIRE_SETS_AVAILABLE("RightTireSetsAvailable"),
    RIGHT_TIRE_SETS_USED("RightTireSetsUsed"),
    ROLL("Roll"),
    ROLL_RATE("RollRate"),
    SESSION_FLAGS("SessionFlags"),
    SESSION_JOKER_LAPS_REMAIN("SessionJokerLapsRemain"),
    SESSION_LAPS_REMAIN("SessionLapsRemain"),
    SESSION_LAPS_REMAIN_EX("SessionLapsRemainEx"),
    SESSION_LAPS_TOTAL("SessionLapsTotal"),
    SESSION_NUM("SessionNum"),
    SESSION_ON_JOKER_LAP("SessionOnJokerLap"),
    SESSION_STATE("SessionState"),
    SESSION_TICK("SessionTick"),
    SESSION_TIME("SessionTime"),
    SESSION_TIME_OF_DAY("SessionTimeOfDay"),
    SESSION_TIME_REMAIN("SessionTimeRemain"),
    SESSION_TIME_TOTAL("SessionTimeTotal"),
    SESSION_UNIQUE_ID("SessionUniqueID"),
    SHIFT_GRIND_RPM("ShiftGrindRPM"),
    SHIFT_INDICATOR_PCT("ShiftIndicatorPct"),
    SHIFT_POWER_PCT("ShiftPowerPct"),
    SKIES("Skies"),
    SOLAR_ALTITUDE("SolarAltitude"),
    SOLAR_AZIMUTH("SolarAzimuth"),
    SPEED("Speed"),
    STEERING_WHEEL_ANGLE1("Steering Wheel Angle"),
    STEERING_WHEEL_TORQUE1("Steering Wheel Torque"),
    STEERING_WHEEL_ANGLE2("SteeringWheelAngle"),
    STEERING_WHEEL_ANGLE_MAX("SteeringWheelAngleMax"),
    STEERING_WHEEL_LIMITER("SteeringWheelLimiter"),
    STEERING_WHEEL_MAX_FORCE_NM("SteeringWheelMaxForceNm"),
    STEERING_WHEEL_PCT_DAMPER("SteeringWheelPctDamper"),
    STEERING_WHEEL_PCT_TORQUE("SteeringWheelPctTorque"),
    STEERING_WHEEL_PCT_TORQUE_SIGN("SteeringWheelPctTorqueSign"),
    STEERING_WHEEL_PCT_TORQUE_SIGN_STOPS("SteeringWheelPctTorqueSignStops"),
    STEERING_WHEEL_TORQUE2("SteeringWheelTorque"),
    STEERING_WHEEL_USE_LINEAR("SteeringWheelUseLinear"),
    SUSP_POS_FL("Susp Pos FL"),
    SUSP_POS_FR("Susp Pos FR"),
    SUSP_POS_RL("Susp Pos RL"),
    SUSP_POS_RR("Susp Pos RR"),
    THROTTLE("Throttle"),
    THROTTLE_POS("Throttle Pos"),
    THROTTLE_RAW("ThrottleRaw"),
    TIRE_LF_RUMBLE_PITCH("TireLF_RumblePitch"),
    TIRE_LR_RUMBLE_PITCH("TireLR_RumblePitch"),
    TIRE_RF_RUMBLE_PITCH("TireRF_RumblePitch"),
    TIRE_RR_RUMBLE_PITCH("TireRR_RumblePitch"),
    TIRE_SETS_AVAILABLE("TireSetsAvailable"),
    TIRE_SETS_USED("TireSetsUsed"),
    TRACK_TEMP("TrackTemp"),
    TRACK_TEMP_CREW("TrackTempCrew"),
    TYRE_PRES_FL("Tyre Pres FL"),
    TYRE_PRES_FR("Tyre Pres FR"),
    TYRE_PRES_RL("Tyre Pres RL"),
    TYRE_PRES_RR("Tyre Pres RR"),
    TYRE_TEMP_FL_CENTRE("Tyre Temp FL Centre"),
    TYRE_TEMP_FL_INNER("Tyre Temp FL Inner"),
    TYRE_TEMP_FL_OUTER("Tyre Temp FL Outer"),
    TYRE_TEMP_FR_CENTRE("Tyre Temp FR Centre"),
    TYRE_TEMP_FR_INNER("Tyre Temp FR Inner"),
    TYRE_TEMP_FR_OUTER("Tyre Temp FR Outer"),
    TYRE_TEMP_RL_CENTRE("Tyre Temp RL Centre"),
    TYRE_TEMP_RL_INNER("Tyre Temp RL Inner"),
    TYRE_TEMP_RL_OUTER("Tyre Temp RL Outer"),
    TYRE_TEMP_RR_CENTRE("Tyre Temp RR Centre"),
    TYRE_TEMP_RR_INNER("Tyre Temp RR Inner"),
    TYRE_TEMP_RR_OUTER("Tyre Temp RR Outer"),
    VELOCITY_X("VelocityX"),
    VELOCITY_Y("VelocityY"),
    VELOCITY_Z("VelocityZ"),
    VERT_ACCEL("VertAccel"),
    VOLTAGE("Voltage"),
    WATER_LEVEL("WaterLevel"),
    WATER_TEMP("WaterTemp"),
    WEATHER_TYPE("WeatherType"),
    WHEEL_SPEED_FL("Wheel Speed FL"),
    WHEEL_SPEED_FR("Wheel Speed FR"),
    WHEEL_SPEED_RL("Wheel Speed RL"),
    WHEEL_SPEED_RR("Wheel Speed RR"),
    WIND_DIR("WindDir"),
    WIND_VEL("WindVel"),
    YAW("Yaw"),
    YAW_NORTH("YawNorth"),
    YAW_RATE("YawRate"),
    DC_ABS("dcABS"),
    DC_BRAKE_BIAS("dcBrakeBias"),
    DC_DASH_PAGE("dcDashPage"),
    DC_FUEL_MIXTURE("dcFuelMixture"),
    DC_HEADLIGHT_FLASH("dcHeadlightFlash"),
    DC_PIT_SPEED_LIMITER_TOGGLE("dcPitSpeedLimiterToggle"),
    DC_STARTER("dcStarter"),
    DC_THROTTLE_SHAPE("dcThrottleShape"),
    DC_TRACTION_CONTROL("dcTractionControl"),
    DC_TRACTION_CONTROL_TOGGLE("dcTractionControlToggle"),
    DP_FAST_REPAIR("dpFastRepair"),
    DP_FUEL_ADD_KG("dpFuelAddKg"),
    DP_FUEL_FILL("dpFuelFill"),
    DP_LFTIRE_CHANGE("dpLFTireChange"),
    DP_LFTIRE_COLD_PRESS("dpLFTireColdPress"),
    DP_LRTIRE_CHANGE("dpLRTireChange"),
    DP_LRTIRE_COLD_PRESS("dpLRTireColdPress"),
    DP_RFTIRE_CHANGE("dpRFTireChange"),
    DP_RFTIRE_COLD_PRESS("dpRFTireColdPress"),
    DP_RRTIRE_CHANGE("dpRRTireChange"),
    DP_RRTIRE_COLD_PRESS("dpRRTireColdPress"),
    DP_WINDSHIELD_TEAROFF("dpWindshieldTearoff");

    companion object {
        fun fromChannelName(name: String): ChannelName {
            return ChannelName.values().first {
                it.varName == name
            }
        }
    }
}
